[package]
name = "Lifer"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.sdl3]
version = "0.14.31"
features = ["build-from-source"]

[dependencies.static_assertions]
version = "1.1.0"
